### ISSUE TITLE
Please don't always colorize the output

### ISSUE THREAD

**Issue by kevgo** [allonsy/currant#2]
Industry best practice is to only print colors if STDOUT is a terminal. In lines like https://github.com/allonsy/currant/blob/master/src/standard_out_api.rs#L144 it always prints the color codes. You get the correct behavior for free when using a crate like https://docs.rs/colored/2.0.0/colored.

**Comment by allonsy** [comment]
Fixed in 
a8a92704b04968070f61932a8b840ae7e93ca12d
