### ISSUE TITLE
Merge the `verbose` and `quiet` concepts

### ISSUE THREAD

**Issue by kevgo** [allonsy/currant#5]
Right now the codebase uses both `verbose` and `quiet`. Both are equivalents of each other. Merging them would simplify things.

**Comment by allonsy** [comment]
really, that was a mistake then, I should have replaced all verbose with quiet

**Comment by allonsy** [comment]
Addressed in #8

**Comment by allonsy** [comment]
closed with 27e998527899535f1c23d44d8328e82a2b0388d2
